課題6. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する #6
fujiki-yuya/flutter_study pull request #10
Opened 2023-06-02 06:54 UTC by fujiki-yuya

## チケットへのリンク

* https://github.com/fujiki-yuya/flutter_study/issues/6

## やったこと
* 上記の課題に取り組みました。現状はニュースの一覧表示と更新だけ完了しています。お気に入り機能はまだ未完成です。

## 画面
![image](https://github.com/fujiki-yuya/flutter_study/assets/86212858/97dd66ee-2c3d-4723-b52e-f75931682308)

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
お気に入り機能は実装途中です。

2023-06-02 08:26 UTC, fujiki-yuya commented
@MinatoIshiwata 
まだ途中ではありますが、ニュースの一覧表示と更新機能はできていますので、そこを一度ご確認いただきたいです。
NEWS API KEYを記述している.envファイルは別途送付いたします。
お気に入り追加機能については完成次第pushいたします。

2023-06-02 08:28 UTC, fujiki-yuya commented on lib/news_screen.dart
> +        onRefresh: getNews,
RefreshIndicatorを使って、リストを引っ張ると再度getNewsを呼び出し、更新されるようにしました。

2023-06-05 07:59 UTC, fujiki-yuya commented
すみませんお気に入り機能はできたのですが、更新するとお気に入りのニュースが消えるので修正中です。

2023-06-06 09:04 UTC, fujiki-yuya commented
freezedの削除は対応済みです。
データの永続化については、sqfliteを使ったやり方で取り組んでいるところです。

2023-06-07 01:02 UTC, MinatoIshiwata commented
@fujiki-yuya 
申し訳ないです。
永続化ですが、Issue内容変更しましたのでご確認のほどよろしくお願いいたします。

2023-06-07 07:13 UTC, fujiki-yuya commented
データの永続化はできるようになりましたが、挙動がおかしかったり、コードの見直しが必要なところが多々あるので修正中です。

2023-06-08 08:40 UTC, fujiki-yuya commented
@MinatoIshiwata 
お気に入りニュースの永続化の対応を行いました。getNews()のコードが長く、責務も多いため、見直しが必要だとは思っていますが、ちょっと時間がかかっており、機能自体は完成していますので、一度レビューをいただきたいです。
よろしくお願いいたします。
すみませんが明日がお休みなので、ご指摘いただいた点は来週修正を行っていきます。

2023-06-09 15:30 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +    }
もう少し良い書き方があると思うので再検討ください🙋

2023-06-09 15:33 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +              child: SafeArea(
ここにSafeArea必要でしょうか？

2023-06-09 15:37 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +    getNews().then((_) => readFavoritesOnStart());
Future.wait内に入れたほうが良いかと思います🙋

2023-06-09 15:38 UTC, MinatoIshiwata commented on lib/file_helper.dart
> +  }
@fujiki-yuya 
ここの意図教えて欲しいです🙋

2023-06-09 15:44 UTC, MinatoIshiwata commented on lib/favorite_news_screen.dart
> +          separatorBuilder: (BuildContext context, int index) {
```suggestion
          separatorBuilder: (context, index) {
```

2023-06-12 05:55 UTC, fujiki-yuya commented on lib/favorite_news_screen.dart
> +          separatorBuilder: (BuildContext context, int index) {
ご提案いただいたように型推論を使った書き方に修正を行いました。

2023-06-12 05:59 UTC, fujiki-yuya commented on lib/news_screen.dart
> +              child: SafeArea(
修正しました。
Scaffoldのbodyに記述しました。

2023-06-12 06:00 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    getNews().then((_) => readFavoritesOnStart());
readFavoritesOnStartはgetNews()の中の最後に呼び出すようにしました。

2023-06-12 06:06 UTC, fujiki-yuya commented on lib/file_helper.dart
> +  }
readFavorites()でファイルの読み書きを行う処理を書いているので、例外としてIOExceptionが起きた時に他に問題が起きないように空のリストを返すようにしました。

2023-06-12 06:14 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    }
favorites.forEach((favorite)のようなforEachを使った書き方をしてみたのですが、lintで警告が出まして、どのような書き方がより良いのかまだ分かっていない状態です。よろしければもう少しヒントをいただけますでしょうか。

2023-06-12 06:16 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘いただいた部分の対応とコメントに返信いたしました。
ご確認お願いいたします。

2023-06-12 14:29 UTC, MinatoIshiwata commented on lib/model/article.dart
> +class Article {
`@immutable` 利用ください🙋

2023-06-12 14:29 UTC, MinatoIshiwata commented on lib/model/news.dart
> +class News{
`@immutable` 利用ください🙋

2023-06-12 14:30 UTC, MinatoIshiwata commented on lib/model/news_result.dart
> +class NewsResult {
`@immutable`

2023-06-12 14:35 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-13 06:04 UTC, fujiki-yuya commented on lib/model/article.dart
> +class Article {
@immutableを付けてフィールドをすべてfinalにし、immutableなクラスに修正を行いました。
お気に入り状態のisFavoriteを更新するために、copyWithメソッドを作成しました。

2023-06-13 06:04 UTC, fujiki-yuya commented on lib/model/news.dart
> +class News{
こちらも同様に@immutableを付けて、immutableクラスにしました。

2023-06-13 06:05 UTC, fujiki-yuya commented on lib/model/news_result.dart
> +class NewsResult {
こちらも修正を行いました。

2023-06-13 06:06 UTC, fujiki-yuya commented on lib/news_screen.dart
> +      final favorites = await readFavorites();
直接readFavorites()を呼び出すようにしました。
作成していたfetchFavorites()は削除しました。

2023-06-13 06:11 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    }).toList();
for文とif文を削除してmapとtoSetを使ったやり方にしました。
お気に入りニュースのurlをsetで取得して、urlがcontainsで一致した場合にお気に入り状態をtrueにするようにしました。

2023-06-13 07:03 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘点の対応を行いました。
ご確認お願いいたします。

2023-06-14 18:49 UTC, MinatoIshiwata commented on lib/file_helper.dart
> +  }
@fujiki-yuya 
exceptionが起きているときに空のリストは不要かと思ったのですが再度見直しをお願いいたします。

2023-06-14 18:52 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +    await readFavoritesOnStart();
exeption発生後にこちらを呼び出す必要はないかと思いますがいかがでしょうか？

2023-06-14 18:53 UTC, MinatoIshiwata commented on lib/news_screen.dart
外部から呼び出さないメソッドはprivate宣言してください🙋

2023-06-14 18:54 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +                        if (url != null) {
早期リターンのほうが可読性高いかと思います🙋

2023-06-14 18:55 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +              const SizedBox(height: 16),
上に16px隙間作るのにこのような書き方をしているのであれば、ListViewにpadding設定できるのでそちらで調整のほうが良いかと思います。

2023-06-15 02:19 UTC, fujiki-yuya commented on lib/news_screen.dart
メソッド見直して外部から呼び出さないものはすべてprivateに修正しました。今後意識していきます。

2023-06-15 02:21 UTC, fujiki-yuya commented on lib/news_screen.dart
> +                        if (url != null) {
```
onTap: () async {
                        final url = _article?[index].url;
                        if (url == null) {
                          return;
                        }
```
urlがnullの場合にreturnするようにしました。

2023-06-15 02:22 UTC, fujiki-yuya commented on lib/news_screen.dart
> +              const SizedBox(height: 16),
```
child: ListView.separated(
     padding: const EdgeInsets.only(top: 16),
```

ListViewのpaddingを使って設定をしました。

2023-06-15 02:34 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    await readFavoritesOnStart();
ご指摘の通りexception発生後に呼び出す必要はなかったです。
それからそもそもこのメソッドは不要でした。
ニュース更新時にお気に入り状態を反映するために作成したのですが、_convertArticlesメソッド(APIで取得したデータをお気に入り状態を持つArticleオブジェクトに入れる)の中で、お気に入り状態のisFavoriteを更新する処理を書いていました。ニュース更新時やアプリ起動時に呼んで、お気に入り状態がUIに反映されるようになっているので、同じような処理をしているreadFavoritesOnStartは不要でした。すみません。

2023-06-15 02:35 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    }).toList();
こちらのメソッド不要でしたので削除しています。

2023-06-15 02:40 UTC, fujiki-yuya commented on lib/file_helper.dart
> +  }
@MinatoIshiwata 
こちら戻り値がリストで、exceptionがお気に入りがないということを想定していて、空のリストを返すようにしたのですが、変えたほうがいいでしょうか？
try catchを削除して、上位で例外処理を行うのが理想でしょうか

2023-06-15 02:42 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘頂いた点の修正を行いました。
お時間ある際にご確認お願いいたします。

2023-06-15 06:15 UTC, fujiki-yuya commented
お気に入りニュース画面ですが、引数でお気に入りニュースのリストを受け取ってそれを表示していたのですが、readFavoritesを使って、お気に入りニュース画面の中でお気に入りのニュースを取得した方がいいと思ったので修正を行いました。

2023-06-16 00:49 UTC, MinatoIshiwata commented on lib/favorite_news_screen.dart
> +              await writeFavorites(favorites);
```suggestion
              await writeFavorites([]);
```

やってること変わらないのでこちらでも良いのですが、`cleanFavorite()` というメソッドを作ったほうが良いかと思います。

2023-06-16 00:49 UTC, MinatoIshiwata commented on lib/favorite_news_screen.dart
> +            } else {
switchのほうが見やすいと思います🙋

2023-06-16 00:50 UTC, MinatoIshiwata commented on lib/favorite_news_screen.dart
> +              final favorites = snapshot.data!;
事前にdataがnullじゃないかif文でチェックしてください🙋

2023-06-16 00:52 UTC, MinatoIshiwata commented on lib/file_helper.dart
> +  }
@fujiki-yuya 
こちらでエラーが起きている際はファイルに何かしらの不具合が生じている状態かと思います。
この状態でアプリが動いたとしても書き込みができない可能性が高いです。
そのため、上位で処理してそもそも画面が表示できない状態が良いのではないでしょうか？

2023-06-16 00:53 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +    return response.articles!;
```suggestion
    return response.articles ?? [];
```

2023-06-16 00:55 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +        _article![index] = article.copyWith(isFavorite: !article.isFavorite);
force-unwrapを利用した場合に_articleがnullだった場合どのような挙動になりますでしょうか？

2023-06-16 00:56 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +                  padding: const EdgeInsets.only(top: 16),
この状態であれば `Column` と `Flexible` はいらないかと思います🙋

2023-06-16 00:56 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
何点かコメントいたしました🙋
ご確認のほどよろしくお願いいたします。

2023-06-16 06:13 UTC, fujiki-yuya commented on lib/favorite_news_screen.dart
> +            } else {
```
switch (snapshot.connectionState) {
              case ConnectionState.waiting:
                return const Center(child: CircularProgressIndicator());
              case ConnectionState.done:
                if (snapshot.hasError) {
                  return Center(child: Text('エラーです ${snapshot.error}'));
                } else if (!snapshot.hasData) {
                  return const Center(child: Text('お気に入りのニュースがありません'));
                } else {
                  final favorites = snapshot.data!;
                  return _favoriteList(favorites);
                }
              case ConnectionState.none:
              case ConnectionState.active:
                return const Center(child: Text('エラー'));
            }
```
switch文を利用して修正しました。bool値が条件のところはif文のままにしています。

2023-06-16 06:14 UTC, fujiki-yuya commented on lib/favorite_news_screen.dart
> +              final favorites = snapshot.data!;
`else if (!snapshot.hasData)`を追加してnullチェックを行うようにしました。

2023-06-16 06:15 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    return response.articles!;
ご指摘頂いた通りに'!'を使わない書き方に修正しました。

2023-06-16 06:15 UTC, fujiki-yuya commented on lib/news_screen.dart
> +                  padding: const EdgeInsets.only(top: 16),
ColumnとFlexibleは不要でしたので削除しました。

2023-06-16 06:17 UTC, fujiki-yuya commented on lib/favorite_news_screen.dart
> +              await writeFavorites(favorites);
```
Future<void> cleanFavorite() async {
    await writeFavorites([]);
  }
```
cleanFavorite()メソッドを作成し、空のリストを渡して更新するように修正しました。

2023-06-16 06:26 UTC, fujiki-yuya commented on lib/file_helper.dart
> +  }
@MinatoIshiwata 
承知いたしました。readFavoritesの中の例外処理は削除しました。上位のtry catchで例外処理を書いています。お気に入りニュース画面の方はFutureBuilderを使っているので、FutureBuilderで例外を受け取って処理(画面にエラーテキスト表示)をするようにしています。

2023-06-16 06:43 UTC, fujiki-yuya commented on lib/news_screen.dart
> +        _article![index] = article.copyWith(isFavorite: !article.isFavorite);
実行時エラーになると思いますので
```
if (_article == null) {
                      return;
                    }
                    _onFavoriteButtonPressed(index);
                  },
```
メソッドの呼び出し前にnullチェックを追加しました。

2023-06-16 06:53 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘頂いた点の対応を行いました。
お時間ある際にご確認お願いいたします。

2023-06-19 16:33 UTC, MinatoIshiwata commented on lib/file_helper.dart
> +  final jsonData = json.decode(contents) as List<dynamic>;
```suggestion
  final jsonData = json.decode(contents) as List<Map<String, dynamic>>;
```
こちらではいかがでしょうか？

2023-06-19 16:36 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +    return response.articles ?? [];
こちらにoptionalありのデータが来ることありそうでしょうか？

2023-06-19 16:38 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +  List<Article>? _article;
optionalにする必要ありますでしょうか？🤔

2023-06-19 16:39 UTC, MinatoIshiwata commented on lib/news_screen.dart
> +      _article![index] = article.copyWith(isFavorite: !article.isFavorite);
force-unwrapしないように処理ください🙋

2023-06-20 05:25 UTC, fujiki-yuya commented on lib/news_screen.dart
> +    return response.articles ?? [];
responseに入るNewsResultの引数articleをrequiredにしました。
optionalありのデータが来ることはないので
`return response.articles;`　に修正しています。

2023-06-20 05:26 UTC, fujiki-yuya commented on lib/news_screen.dart
> +  List<Article>? _article;
こちら修正済みです。面談時にご教示いただいた `late final List<Article> _article;`と定義して
initStateで空のリストを入れています。

2023-06-20 05:27 UTC, fujiki-yuya commented on lib/news_screen.dart
> +      _article![index] = article.copyWith(isFavorite: !article.isFavorite);
_articleがoptionalではなくなったため
`final article = _article[index];`
と修正しました。

2023-06-20 06:07 UTC, fujiki-yuya commented on lib/news_screen.dart
> +            ? const Center(child: CircularProgressIndicator())
bool型で_isLoadingを定義しました。
getNews内で、ニュース取得の処理前にisLoadingをtrueにして、ニュース取得が完了したらisLoadingをfalseにすることで、ニュース取得の処理実行中はローディングインジケータが表示されるようにしています。

2023-06-20 06:11 UTC, fujiki-yuya commented on lib/news_screen.dart
> +            await _getNews();
ニュース一覧に戻ってきた時にgetNews()を実行するようにしました。
これにより、お気に入り画面からニュースを削除して、ニュース一覧に戻るとお気に入り状態が更新されて、最新の状態になるようにしました。
お気に入り状態が更新されるまで少しタイムラグ(getNewsの非同期処理による遅延)があったためローディングインジケータを表示するようにしています。

2023-06-20 06:15 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘点の対応を行いました。
ご確認よろしくお願いいたします。

2023-06-21 06:41 UTC, utamori commented on lib/favorite_news_screen.dart
> +            } else {
@fujiki-yuya 
caseの中でさらにネストするのは可読性下がるので避けましょう
ガード句 'when'を使うことでネストを避けることができます

```dart
 case ConnectionState.done when snapshot.hasError: 処理
 case ConnectionState.done when !snapshot.hasData: 処理
```

また、それぞれのcaseでは値をreturnしているだけなので、switch文ではなく、switch式を使いましょう
```dart
ConnectionState.done when snapshot.hasError => 値,
ConnectionState.done when !snapshot.hasData =>値,
```


https://dart.dev/language/branches#guard-clause

2023-06-21 15:47 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
現状JSONファイルを用意しないと動かないのでそちらの修正をお願いいたします。

2023-06-22 00:48 UTC, fujiki-yuya commented on lib/favorite_news_screen.dart
> +            } else {
```
builder: (context, snapshot) => switch (snapshot.connectionState) {
            ConnectionState.waiting =>
              const Center(child: CircularProgressIndicator()),
            ConnectionState.done when snapshot.hasError =>
              Center(child: Text('エラーです ${snapshot.error}')),
            ConnectionState.done when !snapshot.hasData =>
              const Center(child: Text('お気に入りのニュースがありません')),
            ConnectionState.done => _favoriteList(snapshot.data!),
            ConnectionState.none => const Center(child: Text('エラー')),
            ConnectionState.active => const Center(child: Text('エラー')),
          },
```
whenとswitch式での書き方に修正しました。

2023-06-22 00:52 UTC, fujiki-yuya commented
> @fujiki-yuya 現状JSONファイルを用意しないと動かないのでそちらの修正をお願いいたします。

@MinatoIshiwata 
dotenvを使ったやり方からflutter run --dart-define-from-fileを使ったやり方に修正しました。
JSONファイルはgoogleドライブで共有いたしました。
JSONファイルをルートディレクトリに追加後に
`flutter run --dart-define-from-file=api-keys.json`
こちらのコマンドで動くと思います。　よろしくお願いいたします

2023-06-22 05:08 UTC, MinatoIshiwata commented
@fujiki-yuya 
ファイルがない際にファイルを空のJSONファイルを生成するようにするのは難しいでしょうか？
ご検討のほどよろしくお願いいたします。

2023-06-22 06:01 UTC, fujiki-yuya commented
> @fujiki-yuya ファイルがない際にファイルを空のJSONファイルを生成するようにするのは難しいでしょうか？ ご検討のほどよろしくお願いいたします。

@MinatoIshiwata 
`flutter run --dart-define-from-file=api-keys.json`を実行した際にapi-keys.jsonがない場合は空のjsonファイルが作成されるようにするということで合っていますでしょうか？
また、その場合はシェルスクリプトを用意するような形になると思うのですが、アプローチとしては正しいでしょうか？

2023-06-22 06:06 UTC, MinatoIshiwata commented
@fujiki-yuya 
`favorites.json`が存在しないので動かないということです。
ご確認のほどよろしくお願いいたします。

2023-06-22 07:29 UTC, fujiki-yuya commented
> @fujiki-yuya `favorites.json`が存在しないので動かないということです。 ご確認のほどよろしくお願いいたします。

@MinatoIshiwata 
`api-keys.json`ではなく、`favorites.json`で合っていますでしょうか？
`favorites.json`に関してはニュースをお気に入りとしてJSONで読み書きするためのJSONファイルなので、事前にプロジェクト内に作成するものではなく、存在しない場合には新規作成されるようになっているのではないかと思います。
もしくは`api-keys.json`を空の状態でpushすべきということでしょうか？
認識に誤りがあったらすみません。どのような対応をすべきなのかがまだ分からないので、再度ご教示いただきたいです。
申し訳ありません。

2023-06-22 08:35 UTC, MinatoIshiwata commented
@fujiki-yuya 
私の方で新規インストールした際に`favorites.json`が存在しないエラーが出ておりました。
そのため、見直しが必要がと思います。
アプリを削除して確認してみてください。
ご確認のほどよろしくお願いいたします。

2023-06-23 00:48 UTC, fujiki-yuya commented on lib/file_helper.dart
> +}
@MinatoIshiwata 
すみません確かにアプリを再インストールするとfavorites.jsonが存在しないエラーになりました。
コード修正してファイルがない場合は空のjsonファイルを作成するようにして、エラーがでないように対応を行いました。

2023-06-23 06:07 UTC, fujiki-yuya commented
@MinatoIshiwata 
すみませんAPIキーをコミット履歴から削除する対応でフォースプッシュやコンフリクトの対応を行っています。
今は正常に動くようになっていると思いますので、お時間ある際にご確認いただきたいです。

2023-06-23 14:53 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
.envがないとアプリが起動しない状態なためそちらを修正してください。

2023-06-25 23:59 UTC, fujiki-yuya commented
> @fujiki-yuya .envがないとアプリが起動しない状態なためそちらを修正してください。

@MinatoIshiwata 
こちら対応を行い、.envがなくても起動するようになりました。
pubspec.yamlのassetsに.envを記述していたのが原因でした。
再度ご確認お願いいたします。

2023-06-27 05:15 UTC, MinatoIshiwata approved these changes

2023-06-27 06:13 UTC, merged