課題2.テキストフィールドに入力された文字列を表示するシンプルなToDoリストアプリを作成する
fujiki-yuya/flutter_study pull request #2
Opened 2023-04-17 04:03 UTC by fujiki-yuya

*課題
テキストフィールドに入力された文字列を表示するシンプルなToDoリストアプリを作成する
期限：3日間
追加、削除、編集ができること
一覧表示ができること
同じタイトルが使えない様にする

* このプルリクで何をしたのか？
ToDoアプリの課題に取り組み、必要な機能を実装しました

追加機能-追加ボタンを押すとテキストフォームに入力したテキストをリストに追加できます
編集機能-追加したテキストを押すとダイアログが表示されて、テキストの変更ができます
削除機能-削除ボタンでテキストを削除できます
一覧表示-タスクリストを一覧としてテキストフォームの下に表示します
重複したテキストはアラートダイアログを表示して追加できないようにしました

## 動作確認
それぞれの機能が正常に動くことを確認しました。

https://user-images.githubusercontent.com/86212858/232368948-1c4d13fa-6c7f-4146-a0db-04b5643d9ce6.mp4

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
リストの表示はListView.builderを使いました。
タスクの削除はremoveAtを使いました。

編集時に、すでにあるタスク名に変更しようとするとSnackBarを表示するようにしました。
SnackBarのメッセージが分かりづらいので、よろしければアドバイス等いただきたいです。

必要な機能は完成したと思いますのでプルリクエストを提出します。

2023-04-17 04:59 UTC, MinatoIshiwata commented on lib/todo_app.dart
> +  final TextEditingController _taskController = TextEditingController();
```suggestion
  final _taskController = TextEditingController();
```

2023-04-17 12:43 UTC, MinatoIshiwata commented on lib/todo_app.dart
> +                  title: Text(_taskList[index]),
_taskList[index]を一回定数に置いたほうがわかりやすいですし、変更に対応しやすいです。

2023-04-17 13:04 UTC, MinatoIshiwata commented on lib/todo_app.dart
> +    if (_taskInput.isNotEmpty && !_taskList.contains(_taskInput)) {
`_taskInput`を使う理由ありますでしょうか？🤔

2023-04-17 13:05 UTC, MinatoIshiwata commented on lib/todo_app.dart
> +                    ),
validatorを利用しましょう🙋

2023-04-17 13:06 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-04-17 13:15 UTC, MinatoIshiwata commented on lib/todo_app.dart
ファイル名とクラス名は一致するように変更ください🙋

2023-04-19 05:48 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                  return null;
Validatorの戻り値はString?なので、nullを返すようにしています。

2023-04-19 05:49 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +
_taskInputはフィールドから削除して、_taskController.textを使うようにしました

2023-04-19 05:52 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +class TodoListScreen extends StatefulWidget {
クラス名はUpperCamelCase
ファイル名はlowercase_with_underscores　に修正しました

2023-04-19 05:54 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                String task = _taskList[index];
_taskList[index]を定数に置くようにしました。

2023-04-19 05:58 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +              validator: (value) {
validatorを使うように修正しました。メソッドに書いていたif文の条件はvalidatorの中に記述しています。

2023-04-19 06:15 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                if (editFormKey.currentState!.validate()) {
editFormKey.currentState!.validate()はvalidatorに記述した条件を満たしている場合にtrueになるという認識です。

2023-04-19 06:20 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +              validator: (value) {
Validatorを使うように修正しました。
TextFormFieldはTextFieldと違ってvalidatorを使うことができ、使う際はFormタグで囲み、keyを渡す必要があるという認識です。

2023-04-19 06:21 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                        validator: (value) {
Validatorを使うように修正しました。
TextFormFieldはTextFieldと違ってvalidatorを使うことができ、使う際はFormタグで囲み、keyを渡す必要があるという認識です。

2023-04-19 06:23 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +              validator: (value) {
元々、Snackbarを使っていたのですが、Snackbarは通常のウィジェット階層とは違うようで
ダイアログの上に重ねて表示することはできないのかなと思いました。
今回Validatorについて学んだので、同じように編集時にエラーメッセージを表示するようにしました。

2023-04-19 06:25 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘いただいた点の修正を行いました。ご確認をお願いいたします。

2023-04-19 12:33 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +      _taskController.clear();
こちらはsetStateに入れる必要がなさそうなのですが、入れる理由があれば教えてください🙋

2023-04-19 12:37 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +                    value != _taskList[index]) {
この条件containsだけではうまくいかない感じですか？🤔

2023-04-19 12:43 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +              child: Form(
Formの位置はFormの機能を最低限絞ったほうが良いかと思います🙋

2023-04-19 12:45 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +                String task = _taskList[index];
```suggestion
                final task = _taskList[index];
```

2023-04-19 12:48 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +              padding: const EdgeInsets.all(30),
画面解像度的にできれば8pxの倍数を意識して欲しいです🙋

2023-04-19 12:49 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +              )),
カンマ入れて欲しいです🙋

2023-04-19 19:47 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +    GlobalKey<FormState> editFormKey = GlobalKey<FormState>();
クラス変数でも良い気がします🙋

2023-04-19 19:47 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +    TextEditingController editController =
こちらも都度作らずクラス変数で良い気がします🙋

2023-04-19 19:48 UTC, MinatoIshiwata commented on lib/todo_list_screen.dart
> +      body: Column(
SafeAreaを入れてiOSも考慮しましょう🙋

2023-04-19 19:50 UTC, MinatoIshiwata requested changes
複数点コメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-04-20 08:05 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                  final task = _taskList[index];
Stringからfinalに修正いたしました。

2023-04-20 08:07 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +    _taskController.clear();
_taskControllerはstateを管理しているため、setStateからは外しました。

2023-04-20 08:08 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                    child: Form(
FormはTextFormFieldだけを囲むようにしました。

2023-04-20 08:09 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +              padding: const EdgeInsets.all(32),
paddingは32に修正しました。今後は8の倍数を意識していきます。

2023-04-20 08:12 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +  GlobalKey<FormState> editFormKey = GlobalKey<FormState>();
クラス変数を用意して、editTaskで呼び出すようにしました。

2023-04-20 08:15 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +      body: SafeArea(
レイアウトが崩れるのを防ぐため、SafeAreaを追加しました。

2023-04-20 08:23 UTC, fujiki-yuya commented on lib/todo_list_screen.dart
> +                    value != _taskList[index]) {
分かりにくくなっているためコメントを追加しました。

2023-04-20 08:26 UTC, fujiki-yuya commented
@MinatoIshiwata 
ご指摘いただいた点の修正をいたしました。
ご確認よろしくお願いいたします。

2023-04-20 17:27 UTC, MinatoIshiwata approved these changes
LGTM👍

2023-04-21 00:25 UTC, merged