課題3.ストップウォッチ機能が利用できるアプリを作成する
fujiki-yuya/flutter_study pull request #3
Opened 2023-04-24 06:56 UTC by fujiki-yuya

*課題
ストップウォッチ機能が利用できるアプリを作成する
期限：3日間
ミリ秒単位で表示できること
スタート・ストップ・リセットができること

*このプルリクで何をしたのか？
ストップウォッチアプリの課題に取り組み、必要な機能を実装しました
https://pub.dev/packages/stop_watch_timer
こちらのパッケージを利用しました。

*動作確認

https://user-images.githubusercontent.com/86212858/233901177-11b77f63-d177-4b72-ad8e-5e51e15436bc.mp4

*レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
時間を表示するテキストとボタンを3つ配置しました。
それぞれのボタンの処理は利用したパッケージの
onStartTimer();
onStopTimer();
onResetTimer();
の処理を呼び出すようにしました。

ただ、利用したパッケージのそれぞれの処理の中身を完全には理解できておらず、StreamBuilderのデータの流れもまだ調べながら理解している途中なので、そのあたりを面談時に質問等させてもらいたいです。

機能は完成しているので、一旦プルリクエストを提出いたします。

2023-04-24 06:59 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +              const SizedBox(
ボタンウィジェットの間にSizedBoxを使って余白を入れました

2023-04-24 07:01 UTC, fujiki-yuya commented on pubspec.yaml
> +  stop_watch_timer:
stop_watch_timerパッケージを使っています。

2023-04-24 08:29 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +                builder: (context, snapshot) {
StreamBuilderを使っている箇所ですが、stopWatchTimerのデータの中身が変わるたびに画面の表示を更新する処理を行っているというような認識です。

2023-04-24 08:30 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +              ),
ボタンのウィジェットの間にSizedBoxを使って余白を入れました

2023-04-24 08:31 UTC, fujiki-yuya commented
@MinatoIshiwata  レビューの方をよろしくお願いいたします。

2023-04-24 18:46 UTC, MinatoIshiwata commented on pubspec.yaml
> +  stop_watch_timer:
@fujiki-yuya 
パッケージを利用しないで作成してみてください。

2023-04-26 04:17 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +const SizedBox spacer = SizedBox(height: 24);
SizedBoxを定数にして、呼び出すようにしました。

2023-04-26 04:18 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +            _formatTime(Duration(milliseconds: _stopwatch.elapsedMilliseconds));
_stopwatch.elapsedMillisecondsは、ストップウォッチが開始されてからの時間をミリ秒で返すという認識です

2023-04-26 04:25 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +    int minutes = elapsed.inMinutes % 60;
ミリ秒は '/ 10' で1/100秒単位に変換し、 '.floor()' で少数を切り捨て、 '%100' で100を上限に表示するようにしています。
秒と分は'%60' で60以上表示されなくしています。

2023-04-26 04:26 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +        '${hundredths.toString().padLeft(2, '0')}';
.padLeft(2,'0')で、2桁表示にして、数字が1桁の場合は0を表示するようにしました。

2023-04-26 04:28 UTC, fujiki-yuya commented
@MinatoIshiwata 再度ストップウォッチの実装を行いました。
ご確認よろしくお願いいたします。

2023-04-26 05:28 UTC, MinatoIshiwata commented on lib/stopwatch_screen.dart
> +const SizedBox spacer = SizedBox(height: 24);
ここだけでしか使わない想定でしたら、プライベートに。
他のクラスでも利用可能性がある場合は別ファイルにしてください🙋

2023-04-26 05:37 UTC, MinatoIshiwata commented on lib/stopwatch_screen.dart
> +      _displayTime = "00:00:00:00";
"00:00:00:00"を定数として定義しておいて、初期化する際に利用してみてはいかがでしょうか？

2023-04-26 05:37 UTC, MinatoIshiwata commented on lib/stopwatch_screen.dart
> +    _stopwatch.reset();
カスケードで呼び出しできそうですがいかがでしょうか？

2023-04-26 05:38 UTC, MinatoIshiwata commented on lib/stopwatch_screen.dart
> +        '${hundredths.toString().padLeft(2, '0')}';
同じ処理何回もしているので、intの拡張にゲッター作成してみてはいかがでしょうか？

2023-04-26 07:00 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +}
intの拡張メソッドを用意しました。

2023-04-26 07:01 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +      ..reset();
カスケード記法を使いました。

2023-04-26 07:02 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +const SizedBox _spacer = SizedBox(height: 24);
spacerをプライベートにしました。

2023-04-26 07:05 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +      _displayTime = _initialDisplayTime;
"00:00:00:00"を定数とした_initialDisplayTimeを利用するようにしました。

2023-04-26 07:09 UTC, fujiki-yuya commented
@MinatoIshiwata 　ご指摘いただいた点の対応を行いました。ご確認よろしくお願いいたします。

2023-04-26 08:40 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
Androidの小さい端末はいい感じですが、大きい端末だと数字がぶれて見えるので調整してみてください🙋

2023-04-27 00:58 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +              ),
TextのstyleにfontFeaturesを追加して、数字のぶれを改善しました。
fontFeaturesは数字が等幅になり、テキストの位置が変わらなくなるため、ぶれることがなくなるという認識です。

その他、fontFamilyを使ったやり方で
style: TextStyle(fontSize: 40, fontFamily: 'Courier'),
Courierで等幅になり、同じように解決できることを確認しました。

2023-04-27 01:02 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +    _timer = Timer.periodic(const Duration(milliseconds: 10), (Timer timer) {
Duration(milliseconds: 1) 　→　Duration(milliseconds: 10) に修正しました。
1ミリ秒での画面の更新は過剰のようで、画面の描画が不安定になるみたいなので変更しました。

2023-04-27 01:04 UTC, fujiki-yuya commented
@MinatoIshiwata  ご指摘いただいた数字のぶれのところを対応してみました。
ご確認よろしくお願いいたします。

2023-04-27 02:26 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +}
拡張メソッドをprivateにしました

2023-04-27 03:03 UTC, MinatoIshiwata approved these changes
LGTMですが、東さんにもレビューいただきましょう🙋
ご確認のほどよろしくお願いいたします。

2023-05-09 07:18 UTC, azuma-takuya commented on lib/stopwatch_screen.dart
> +      _displayTime = _initialDisplayTime;
const Durationを_displayTimeに代入する方法でも、
変数_initialDisplayTimeを使わずに初期化することができると思います。

2023-05-09 07:26 UTC, fujiki-yuya commented on lib/stopwatch_screen.dart
> +      _displayTime = _initialDisplayTime;
@azuma-takuya 
レビューありがとうございます。修正しましたのでご確認をお願いいたします。

2023-05-09 07:27 UTC, azuma-takuya approved these changes

2023-05-09 07:27 UTC, azuma-takuya approved these changes

2023-05-09 07:28 UTC, merged