課題4. 本のバーコードをスキャンしてISBN値を元にAmazonの商品ページを表示する #4
fujiki-yuya/flutter_study pull request #7
Opened 2023-05-08 06:59 UTC by fujiki-yuya

## チケットへのリンク

* https://github.com/fujiki-yuya/flutter_study/issues/4

## このプルリクで何をしたのか？
・上記の課題4に取り組みました。JANコードからISBNを取得し、amazonの商品ページを表示するアプリを作成しました。

## 動作確認
連続スキャンができるようにしました。
https://user-images.githubusercontent.com/86212858/236755512-9b21c173-11f9-4ee1-8f5b-1223219b6c00.mp4

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
バーコードスキャンはbarcode_scan2を使用しました。

2023-05-08 07:54 UTC, fujiki-yuya commented on pubspec.yaml
> +  webview_flutter: ^2.3.0
商品ページの表示はこちらのwebviewを使いました。

2023-05-08 07:55 UTC, fujiki-yuya commented on lib/webview_screen.dart
> +          javascriptMode: JavascriptMode.unrestricted,
Javascriptをonにすることで、amazonの商品ページの画像が読み込まれるようになりました。

2023-05-08 08:29 UTC, fujiki-yuya commented on lib/search_screen.dart
> +  }
Navigatorを使って画面遷移をするようにしました。
pushで画面を上に重ね、popで画面を閉じるという認識です。

MaterialPageRouteとbuilderを使って、新しいurlのWebViewScreenを作成しています。

2023-05-08 08:47 UTC, fujiki-yuya commented
@MinatoIshiwata 
完成しましたので、コードレビューをよろしくお願いいたします。

2023-05-09 02:50 UTC, MinatoIshiwata commented on android/app/build.gradle
> +        minSdkVersion 19
こちら変更事由あれば教えて下さい🙋

2023-05-09 03:01 UTC, MinatoIshiwata commented on lib/search_screen.dart
> +  }
Extensionにしてしまったほうがスッキリしそうです🙋

2023-05-09 03:15 UTC, MinatoIshiwata commented on lib/search_screen.dart
> +    String barcodeScanResult = '';
この変数見直してください🙋

2023-05-09 03:16 UTC, MinatoIshiwata commented on lib/search_screen.dart
> +          );
こちら独立したクラスやメソッドにすると恐らくもう少し見やすくなるかと思います🙋

2023-05-09 03:17 UTC, MinatoIshiwata commented on lib/search_screen.dart
> +                      ),
こちら閉じるように処理してください🙋

2023-05-09 03:21 UTC, MinatoIshiwata commented on lib/search_screen.dart
> +      }
ここもう少し安全性の配慮必要ですね…

2023-05-11 07:23 UTC, fujiki-yuya commented on lib/search_screen.dart
> +    String barcodeScanResult = '';
変数barcodeScanResultは削除して、result.rawContentを_navigateToWebViewに渡すように修正しました

2023-05-11 07:26 UTC, fujiki-yuya commented on lib/jan_to_isbn_string_extension.dart
ISBNへの変換処理を拡張メソッドにして、別ファイルにしました。
例外処理を追加して安全性を配慮しました。

2023-05-11 07:29 UTC, fujiki-yuya commented on lib/scan_result_dialog.dart
スキャン後に表示するAlertDialogウィジェットをクラスに分けました。

2023-05-11 07:36 UTC, fujiki-yuya commented on lib/search_screen.dart
> +    FocusScope.of(context).unfocus();
キーボードが開きっぱなしにならないように、バーコードスキャンを開いたタイミングでフォーカスを外してキーボードを閉じるようにしました。

2023-05-11 07:44 UTC, fujiki-yuya commented on android/app/build.gradle
> +        minSdkVersion 19
https://pub.dev/packages/webview_flutter
こちらのwebviewなんですが、minSdkVersionが19より低いと動かないようで、実際にflutter.minSdkVersionだとエラーになってしまったので19に変更を行いました。

2023-05-11 07:46 UTC, fujiki-yuya commented on ios/Runner/Info.plist
> +    <string>Camera permission is required for barcode scanning.</string>
iOSの方のカメラパーミッションを追加しました。
東さんのiPhoneでスキャンの起動を確認できました。

2023-05-11 07:57 UTC, fujiki-yuya commented
@MinatoIshiwata ご指摘いただいた点の修正を行いました。ご確認お願いいたします。
続けてPACERのスキャン機能を使って実装してみようと思います。

2023-05-12 02:06 UTC, MinatoIshiwata commented on lib/jan_to_isbn_string_extension.dart
> +      }
これもOKですが、forEachでisbnを回したり、isbnを回す分なのでlengthを利用したりでご対応ください🙋

2023-05-12 02:06 UTC, MinatoIshiwata commented on lib/jan_to_isbn_string_extension.dart
マジックナンバーに名前つけましょう🙋

2023-05-12 02:31 UTC, MinatoIshiwata commented on lib/scan_result_dialog.dart
@fujiki-yuya 
staticメソッドでshowなどを作って表示部分もこちらにまとめましょう🙋

2023-05-12 04:26 UTC, MinatoIshiwata requested changes
@fujiki-yuya 
一通り確認いたしました。
ご確認のほどよろしくお願いいたします。

2023-05-12 09:26 UTC, fujiki-yuya commented
マジックナンバーを定数として定義(https://github.com/fujiki-yuya/flutter_study/pull/7#discussion_r1191839075)、
スキャン後のダイアログのshowDialogをメソッド化(https://github.com/fujikiyuya/flutter_study/pull/7#discussion_r1191849299)まではpush済みです。

2023-05-14 16:15 UTC, MinatoIshiwata commented on lib/jan_to_isbn_string_extension.dart
> +        }
for-inやmapやjoinなど活用してください🙋

2023-05-14 16:40 UTC, MinatoIshiwata reviewed
何点かコメントいたしました🙋

2023-05-16 08:23 UTC, fujiki-yuya commented on lib/jan_to_isbn_string_extension.dart
> +        }).reduce((value, element) => value + element);
asMapはリストの要素にindex番号をつけてmapにする、
entriesはリストの要素と要素番号のセットの情報、
reduceで要素を1つにする、という認識です。
チェックデジットの計算ロジックに基づきindex+1を最初の桁から計算した結果をreduceで入れて、以前と同様の処理を実装しました。

2023-05-16 08:29 UTC, fujiki-yuya commented on lib/search_screen.dart
> +    return GestureDetector(
ScaffoldをGestureDetectorで囲むことで、テキストフィールド以外をタップしたときに、キーボードが閉じるようになりました。SafeAreaを囲んでもキーボードは閉じられなかったので、Scaffoldを囲みました。他のボタンの動作は正常に動くことを確認済みです。

2023-05-16 08:31 UTC, fujiki-yuya commented
@MinatoIshiwata  チェックデジット計算のfor文のところの修正と空白タップでキーボードを閉じる処理の追加を行いました。ご確認よろしくお願いいたします。

2023-05-17 04:08 UTC, MinatoIshiwata commented on lib/jan_to_isbn_string_extension.dart
> +        }).reduce((value, element) => value + element);
いい感じにまとまりましたね🙋

2023-05-17 06:37 UTC, MinatoIshiwata commented on lib/jan_to_isbn_string_extension.dart
> +    int checkDigitXValue = 10;
可能か確認して無くて申し訳ないですが、メソッド外に定義可能であればそのようにお願いいたします。（メソッド呼ぶ度に初期化不要かと思いますので。

2023-05-17 06:39 UTC, MinatoIshiwata approved these changes
@fujiki-yuya 
1点だけ確認いただけましたらOKです。
ご確認のほどよろしくお願いいたします。

2023-05-18 08:32 UTC, fujiki-yuya commented
@MinatoIshiwata  Dart Analysisの警告はすべて対応を行いました。以前の課題のコードにも多くの警告がでていたので、今回すべて修正してpushしています。問題なさそうであれば、今回の対応で今課題は終了になるかと思います。よろしくお願いいたします。

2023-05-18 15:48 UTC, MinatoIshiwata approved these changes
LGTM

2023-05-19 00:12 UTC, merged